source 'http://rubygems.org'

gem 'rails', '>=3.0.0'
# gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'sqlite3'

#START_HIGHLIGHT
group :development, :test do
  gem "rspec-rails", ">= 2.0.0"
  gem "webrat", ">= 0.7.2"
end
group :test do
  gem "cucumber-rails", ">= 0.3.2"
  gem 'database_cleaner'
end
#END_HIGHLIGHT

